# Generated by Django 5.1.7 on 2025-03-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_userprofile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
