# Generated by Django 5.1.7 on 2025-03-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_userprofile_address_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='profile_pics/'),
        ),
    ]
